export interface InstrumentDef {
  symbol: string
  name: string
  assetClass: 'stock' | 'etf'
  sector: string
  description: string
  basePrice: number
  driftPerYear: number
  volatility: number
  shares: number // millions
  eps: number
  dividendYield: number
  color: string
}

export const INSTRUMENT_DEFS: InstrumentDef[] = [
  { symbol: 'AAPL', name: 'Apple Inc.', assetClass: 'stock', sector: 'Technology', description: 'Designs, manufactures and markets smartphones, personal computers, wearables and services, anchored by the iPhone and a large installed device base.', basePrice: 120, driftPerYear: 0.18, volatility: 0.016, shares: 15200, eps: 6.6, dividendYield: 0.5, color: '#8fd6ff' },
  { symbol: 'MSFT', name: 'Microsoft Corporation', assetClass: 'stock', sector: 'Technology', description: 'Builds enterprise and consumer software, cloud infrastructure (Azure), and productivity platforms including Office and LinkedIn.', basePrice: 250, driftPerYear: 0.2, volatility: 0.015, shares: 7430, eps: 12.4, dividendYield: 0.7, color: '#7ee0a8' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation', assetClass: 'stock', sector: 'Semiconductors', description: 'Designs GPUs and accelerated computing platforms that power gaming, data centers and AI training/inference workloads.', basePrice: 20, driftPerYear: 0.55, volatility: 0.032, shares: 24600, eps: 2.9, dividendYield: 0.03, color: '#3ddc84' },
  { symbol: 'TSLA', name: 'Tesla, Inc.', assetClass: 'stock', sector: 'Automotive', description: 'Manufactures electric vehicles, energy storage and solar products, with growing bets on autonomy and robotics.', basePrice: 120, driftPerYear: 0.24, volatility: 0.038, shares: 3190, eps: 3.1, dividendYield: 0, color: '#ff5c72' },
  { symbol: 'AMZN', name: 'Amazon.com, Inc.', assetClass: 'stock', sector: 'Consumer Discretionary', description: 'Global e-commerce and logistics operator, and the largest provider of cloud infrastructure through AWS.', basePrice: 100, driftPerYear: 0.22, volatility: 0.02, shares: 10400, eps: 4.5, dividendYield: 0, color: '#ffb74a' },
  { symbol: 'GOOGL', name: 'Alphabet Inc.', assetClass: 'stock', sector: 'Communication Services', description: 'Parent of Google Search, YouTube, Android and Google Cloud, with substantial investment in AI research.', basePrice: 90, driftPerYear: 0.18, volatility: 0.018, shares: 12100, eps: 6.9, dividendYield: 0.4, color: '#4f8cff' },
  { symbol: 'META', name: 'Meta Platforms, Inc.', assetClass: 'stock', sector: 'Communication Services', description: 'Operates Facebook, Instagram and WhatsApp, and invests heavily in AI-driven ad ranking and mixed reality.', basePrice: 180, driftPerYear: 0.26, volatility: 0.024, shares: 2540, eps: 22.1, dividendYield: 0.3, color: '#9b7bff' },
  { symbol: 'AMD', name: 'Advanced Micro Devices, Inc.', assetClass: 'stock', sector: 'Semiconductors', description: 'Designs CPUs and GPUs for PCs, servers and data centers, competing directly in the AI accelerator market.', basePrice: 60, driftPerYear: 0.24, volatility: 0.03, shares: 1620, eps: 2.6, dividendYield: 0, color: '#ff8f6b' },
  { symbol: 'NFLX', name: 'Netflix, Inc.', assetClass: 'stock', sector: 'Communication Services', description: 'Subscription streaming entertainment service with a large slate of original film and television content.', basePrice: 300, driftPerYear: 0.2, volatility: 0.022, shares: 430, eps: 19.8, dividendYield: 0, color: '#ff5c72' },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.', assetClass: 'stock', sector: 'Financials', description: 'The largest U.S. bank by assets, spanning consumer banking, investment banking, and asset management.', basePrice: 120, driftPerYear: 0.14, volatility: 0.014, shares: 2900, eps: 17.2, dividendYield: 2.1, color: '#8fd6ff' },
  { symbol: 'V', name: 'Visa Inc.', assetClass: 'stock', sector: 'Financials', description: 'Operates the largest global electronic payments network, connecting consumers, merchants and banks.', basePrice: 180, driftPerYear: 0.15, volatility: 0.013, shares: 2050, eps: 9.9, dividendYield: 0.7, color: '#7ee0a8' },
  { symbol: 'DIS', name: 'The Walt Disney Company', assetClass: 'stock', sector: 'Communication Services', description: 'Media and entertainment conglomerate spanning studios, streaming, theme parks and consumer products.', basePrice: 140, driftPerYear: 0.04, volatility: 0.02, shares: 1810, eps: 4.2, dividendYield: 0.9, color: '#4f8cff' },
  { symbol: 'KO', name: 'The Coca-Cola Company', assetClass: 'stock', sector: 'Consumer Staples', description: 'Global beverage company with a portfolio of nonalcoholic drink brands distributed in over 200 countries.', basePrice: 55, driftPerYear: 0.07, volatility: 0.009, shares: 4320, eps: 2.7, dividendYield: 2.8, color: '#ffb74a' },
  { symbol: 'PFE', name: 'Pfizer Inc.', assetClass: 'stock', sector: 'Healthcare', description: 'Research-based pharmaceutical company developing vaccines and medicines across major therapeutic areas.', basePrice: 40, driftPerYear: -0.03, volatility: 0.017, shares: 5650, eps: 1.6, dividendYield: 6.1, color: '#9b7bff' },
  { symbol: 'XOM', name: 'Exxon Mobil Corporation', assetClass: 'stock', sector: 'Energy', description: 'Integrated oil and gas major engaged in exploration, refining, chemicals and low-carbon energy ventures.', basePrice: 70, driftPerYear: 0.09, volatility: 0.017, shares: 4230, eps: 8.9, dividendYield: 3.3, color: '#ffb74a' },
  { symbol: 'BA', name: 'The Boeing Company', assetClass: 'stock', sector: 'Industrials', description: 'Designs and manufactures commercial airplanes, defense systems and space technology.', basePrice: 200, driftPerYear: -0.02, volatility: 0.026, shares: 620, eps: -3.4, dividendYield: 0, color: '#ff5c72' },
  { symbol: 'CRM', name: 'Salesforce, Inc.', assetClass: 'stock', sector: 'Technology', description: 'Provides cloud-based customer relationship management software and an expanding AI agent platform.', basePrice: 150, driftPerYear: 0.13, volatility: 0.021, shares: 960, eps: 6.1, dividendYield: 0.6, color: '#7ee0a8' },
  { symbol: 'ORCL', name: 'Oracle Corporation', assetClass: 'stock', sector: 'Technology', description: 'Enterprise database, applications and rapidly growing cloud infrastructure provider for large organizations.', basePrice: 60, driftPerYear: 0.24, volatility: 0.021, shares: 2760, eps: 4.8, dividendYield: 0.9, color: '#8fd6ff' },
  { symbol: 'ADBE', name: 'Adobe Inc.', assetClass: 'stock', sector: 'Technology', description: 'Creative, document and marketing software maker behind Photoshop, Acrobat and the Creative Cloud suite.', basePrice: 340, driftPerYear: 0.1, volatility: 0.019, shares: 440, eps: 13.9, dividendYield: 0, color: '#ff8f6b' },
  { symbol: 'INTC', name: 'Intel Corporation', assetClass: 'stock', sector: 'Semiconductors', description: 'Designs and manufactures processors and is rebuilding advanced chip manufacturing (foundry) capacity.', basePrice: 45, driftPerYear: -0.08, volatility: 0.025, shares: 4270, eps: 0.4, dividendYield: 0.5, color: '#4f8cff' },
  { symbol: 'UBER', name: 'Uber Technologies, Inc.', assetClass: 'stock', sector: 'Technology', description: 'Operates on-demand mobility and delivery marketplaces connecting riders, drivers, and merchants worldwide.', basePrice: 30, driftPerYear: 0.22, volatility: 0.024, shares: 2110, eps: 2.1, dividendYield: 0, color: '#3ddc84' },
  { symbol: 'PYPL', name: 'PayPal Holdings, Inc.', assetClass: 'stock', sector: 'Financials', description: 'Digital payments platform enabling online checkout, peer-to-peer transfers and merchant services.', basePrice: 90, driftPerYear: -0.02, volatility: 0.023, shares: 1030, eps: 4.6, dividendYield: 0, color: '#8fd6ff' },
  { symbol: 'COIN', name: 'Coinbase Global, Inc.', assetClass: 'stock', sector: 'Financials', description: 'Operates a leading cryptocurrency exchange and custody platform for retail and institutional clients.', basePrice: 60, driftPerYear: 0.35, volatility: 0.05, shares: 250, eps: 1.8, dividendYield: 0, color: '#ffb74a' },
  { symbol: 'PLTR', name: 'Palantir Technologies Inc.', assetClass: 'stock', sector: 'Technology', description: 'Builds data integration and AI decision-support software for government and commercial enterprises.', basePrice: 8, driftPerYear: 0.5, volatility: 0.045, shares: 2260, eps: 0.2, dividendYield: 0, color: '#9b7bff' },
  { symbol: 'SBUX', name: 'Starbucks Corporation', assetClass: 'stock', sector: 'Consumer Discretionary', description: 'Roasts and retails specialty coffee through company-operated and licensed stores worldwide.', basePrice: 90, driftPerYear: 0.02, volatility: 0.016, shares: 1140, eps: 2.9, dividendYield: 2.5, color: '#7ee0a8' },
  { symbol: 'SHOP', name: 'Shopify Inc.', assetClass: 'stock', sector: 'Technology', description: 'Provides commerce software that lets merchants build, run and grow online and in-person retail businesses.', basePrice: 40, driftPerYear: 0.26, volatility: 0.03, shares: 1280, eps: 0.9, dividendYield: 0, color: '#3ddc84' },

  { symbol: 'SPY', name: 'SPDR S&P 500 ETF Trust', assetClass: 'etf', sector: 'Broad Market', description: 'Tracks the S&P 500 index, offering diversified exposure to 500 large U.S. companies.', basePrice: 300, driftPerYear: 0.11, volatility: 0.009, shares: 900, eps: 0, dividendYield: 1.2, color: '#8fd6ff' },
  { symbol: 'QQQ', name: 'Invesco QQQ Trust', assetClass: 'etf', sector: 'Technology', description: 'Tracks the Nasdaq-100, concentrated in large-cap technology and growth companies.', basePrice: 250, driftPerYear: 0.16, volatility: 0.013, shares: 460, eps: 0, dividendYield: 0.6, color: '#3ddc84' },
  { symbol: 'VOO', name: 'Vanguard S&P 500 ETF', assetClass: 'etf', sector: 'Broad Market', description: 'Low-cost fund tracking the S&P 500, popular as a core long-term portfolio holding.', basePrice: 280, driftPerYear: 0.11, volatility: 0.009, shares: 950, eps: 0, dividendYield: 1.2, color: '#4f8cff' },
  { symbol: 'VTI', name: 'Vanguard Total Stock Market ETF', assetClass: 'etf', sector: 'Broad Market', description: 'Tracks the entire U.S. investable equity market across large, mid and small-cap companies.', basePrice: 150, driftPerYear: 0.11, volatility: 0.009, shares: 1000, eps: 0, dividendYield: 1.3, color: '#7ee0a8' },
  { symbol: 'ARKK', name: 'ARK Innovation ETF', assetClass: 'etf', sector: 'Innovation', description: 'Actively managed fund concentrated in disruptive innovation themes such as genomics, robotics and AI.', basePrice: 90, driftPerYear: 0.05, volatility: 0.033, shares: 150, eps: 0, dividendYield: 0, color: '#ff5c72' },
  { symbol: 'GLD', name: 'SPDR Gold Shares', assetClass: 'etf', sector: 'Commodities', description: 'Exchange-traded fund backed by physical gold bullion, tracking the price of gold.', basePrice: 110, driftPerYear: 0.1, volatility: 0.009, shares: 320, eps: 0, dividendYield: 0, color: '#ffb74a' },
]
